apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: test-gateway 
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*.brandontksmith.com"
    - "brandontksmith.com" # UPDATE the domain name
    port:
      name: http
      number: 80
      protocol: HTTP
