apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: test-gateway 
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - "argocd.brandon.local"
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: argocd-credential
