loki:
  serviceMonitor:
    enabled: true
  serviceAccount:
    create: true
    name: loki
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::066731752683:role/LokiRole
  loki:
    auth_enabled: false
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    storage_config:
      aws:
        region: us-east-1
        bucketnames: loki-chunks-brandon-test,loki-ruler-brandon-test
        s3forcepathstyle: false
    pattern_ingester:
      enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
      retention_period: 72h
    querier:
      max_concurrent: 4
    
    commonConfig:
      replication_factor: 1

    storage:
      type: s3
      bucketNames:
        chunks: loki-chunks-brandon-test
        ruler: loki-ruler-brandon-test

  deploymentMode: SimpleScalable

  backend:
    replicas: 1
    persistence:
      storageClass: gp2

  chunksCache:
    enabled: false

  read:
    replicas: 1

  write:
    replicas: 1
    persistence:
      storageClass: gp2

  minio:
    enabled: false
