mimir:
  serviceAccount:
    create: true
    name: mimir
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::066731752683:role/MimirRole

  mimir:
    structuredConfig:
      common:
        storage:
          backend: s3
          s3:
            endpoint: s3.us-east-1.amazonaws.com
            bucket_name: mimor
            region: us-east-1
      blocks_storage:
        s3:
          bucket_name: mimir-blocks-brandon-test
      alertmanager_storage:
        s3:
          bucket_name: mimir-alertmanager-brandon-test
      ruler_storage:
        s3:
          bucket_name: mimir-ruler-brandon-test

  alertmanager:
    enabled: false
    persistentVolume:
      enabled: true
      storageClass: gp2
    replicas: 2
    resources:
      limits:
        memory: 1.4Gi
      requests:
        cpu: 1
        memory: 1Gi
    statefulSet:
      enabled: true

  compactor:
    # Supports 1M Metric Series
    # persistentVolume:
    #   size: 20Gi
    # replicas: 1
    # resources:
    #   limits:
    #     memory: 2.1Gi
    #   requests:
    #     cpu: 1
    #     memory: 1.5Gi
    persistentVolume:
      size: 10Gi
      storageClass: gp2
    replicas: 1
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi

  distributor:
    # Supports 1M Metric Series
    # replicas: 2
    # resources:
    #   limits:
    #     memory: 5.7Gi
    #   requests:
    #     cpu: 2
    #     memory: 4Gi
    replicas: 1
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi

  ingester:
    # Supports 1M Metric Series
    # persistentVolume:
    #   size: 50Gi
    # replicas: 3
    # resources:
    #   limits:
    #     memory: 12Gi
    #   requests:
    #     cpu: 3.5
    #     memory: 8Gi
    persistentVolume:
      size: 10Gi
      storageClass: gp2
    replicas: 1
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    topologySpreadConstraints: {}
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: target # support for enterprise.legacyLabels
                  operator: In
                  values:
                    - ingester
            topologyKey: 'kubernetes.io/hostname'

          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - ingester
            topologyKey: 'kubernetes.io/hostname'

    zoneAwareReplication:
      topologyKey: 'kubernetes.io/hostname'

  admin-cache:
    enabled: false
    replicas: 1

  chunks-cache:
    enabled: false
    replicas: 1

  index-cache:
    enabled: false
    replicas: 1

  metadata-cache:
    enabled: false
    replicas: 1

  results-cache:
    enabled: false
    replicas: 1

  minio:
    enabled: false

  overrides_exporter:
    replicas: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  querier:
    # Supports 1M Metric Series
    # replicas: 1
    # resources:
    #   limits:
    #     memory: 5.6Gi
    #   requests:
    #     cpu: 2
    #     memory: 4Gi
    replicas: 1
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi

  query_frontend:
    # Supports 1M Metric Series
    # replicas: 1
    # resources:
    #   limits:
    #     memory: 2.8Gi
    #   requests:
    #     cpu: 2
    #     memory: 2Gi
    replicas: 1
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi

  ruler:
    # Supports 1M Metric Series
    # replicas: 1
    # resources:
    #   limits:
    #     memory: 2.8Gi
    #   requests:
    #     cpu: 1
    #     memory: 2Gi
    replicas: 1
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi

  store_gateway:
    # Supports 1M Metric Series
    # persistentVolume:
    #   size: 10Gi
    # replicas: 3
    # resources:
    #   limits:
    #     memory: 2.1Gi
    #   requests:
    #     cpu: 1
    #     memory: 1.5Gi
    persistentVolume:
      size: 10Gi
      storageClass: gp2
    replicas: 1
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi

    topologySpreadConstraints: {}
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: target # support for enterprise.legacyLabels
                  operator: In
                  values:
                    - store-gateway
            topologyKey: 'kubernetes.io/hostname'

          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - store-gateway
            topologyKey: 'kubernetes.io/hostname'
    zoneAwareReplication:
      topologyKey: 'kubernetes.io/hostname'

  nginx:
    replicas: 1
    resources:
      limits:
        memory: 731Mi
      requests:
        cpu: 250m
        memory: 512Mi
