tempo:
  serviceAccount:
    create: true
    name: tempo
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::066731752683:role/TempoRole

  tempo:
    storage:
      trace:
        backend: s3
        s3:
          region: us-east-1
          endpoint: s3.us-east-1.amazonaws.com
          bucket: tempo-brandon-test

    metricsGenerator:
      enabled: true
      remoteWriteUrl: http://mimir-nginx.monitoring.svc.cluster.local:80/api/v1/push
