apiVersion: v2
name: alloy
description: Umbrella chart for alloy
type: application
version: 0.1.0
appVersion: v1.7.2
dependencies:
  - name: alloy
    version: 0.12.3
    repository: https://grafana.github.io/helm-charts
