prometheus:
  server:
    persistentVolume:
      size: 8Gi
      storageClass: gp2
  alertmanager:
    enabled: true
    alertmanager:
      persistence:
        size: 4Gi
        storageClass: gpt2
