apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/brandontksmith/k8s-test-apps.git
      revision: HEAD
      directories:
      - path: apps/dev/*    
  template:      
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 2}}' 
    spec:
      project: default

      source:
        repoURL: https://github.com/brandontksmith/k8s-test-apps.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      
      destination:
        server: https://kubernetes.default.svc
        namespace: 'dev'

      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true
