apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
      - cluster: stg
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: apps-{{.cluster}}
    spec:
      project: default
      source:
        repoURL: https://github.com/brandontksmith/k8s-test-apps.git
        targetRevision: HEAD
        path: apps/{{.cluster}}/**
      destination:
        server: '{{.url}}'
        namespace: '{{.cluster}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true  
        automated: 
          prune: true 
          selfHeal: true
